import { describe, it, expect } from "vitest";
import { existsSync } from "node:fs";
import { resolveCorpus, listCorpora } from "../src/workload/corpus.js";
import { loadTasks } from "../src/workload/load.js";

describe("corpus", () => {
  it("lists the shipped archetypes with versions", () => {
    const corpora = listCorpora();
    const names = corpora.map((c) => c.archetype);
    expect(names).toContain("filesystem");
    expect(names).toContain("fetch");
    expect(corpora.find((c) => c.archetype === "filesystem")!.versions).toContain(1);
  });

  it("resolves <archetype>@<version> and bare <archetype> (latest)", () => {
    const pinned = resolveCorpus("filesystem@1");
    expect(existsSync(pinned)).toBe(true);
    expect(pinned.endsWith("v1.yaml")).toBe(true);
    expect(resolveCorpus("filesystem")).toBe(pinned); // latest === v1
  });

  it("throws on an unknown archetype", () => {
    expect(() => resolveCorpus("nope")).toThrow(/unknown corpus archetype/);
  });

  it("every shipped corpus parses into tasks with human-written criteria", async () => {
    for (const { archetype, versions } of listCorpora()) {
      for (const v of versions) {
        const tasks = await loadTasks(resolveCorpus(`${archetype}@${v}`));
        expect(tasks.length).toBeGreaterThan(0);
        for (const t of tasks) {
          expect(t.criteria.length).toBeGreaterThan(0);
          expect(t.criteriaAutoGenerated).toBe(false); // human-written → correctness is not "indicative"
          expect(t.prompt || (t.turns && t.turns.length)).toBeTruthy();
        }
      }
    }
  });
});
