import { describe, it, expect } from "vitest";
import { buildJudgeUser, scoreFromVerdicts } from "../src/score/judge.js";
import type { JudgeResult, Task } from "../src/types.js";

// Re-implement parse via the exported pieces by exercising scoreFromVerdicts and
// the prompt builder; extractJson/parseVerdicts are internal but covered through
// scoreFromVerdicts on representative verdict sets.

describe("scoreFromVerdicts", () => {
  it("maps PASS=1, PARTIAL=0.5, FAIL=0 and averages", () => {
    const v: JudgeResult[] = [
      { criterion: "a", verdict: "PASS", reason: "" },
      { criterion: "b", verdict: "PARTIAL", reason: "" },
      { criterion: "c", verdict: "FAIL", reason: "" },
      { criterion: "d", verdict: "PASS", reason: "" },
    ];
    expect(scoreFromVerdicts(v)).toBeCloseTo((1 + 0.5 + 0 + 1) / 4, 6);
  });
  it("returns 0 for empty", () => {
    expect(scoreFromVerdicts([])).toBe(0);
  });
});

describe("buildJudgeUser", () => {
  it("includes single-turn prompt, criteria, and answer", () => {
    const task: Task = {
      id: "t1",
      category: "baseline",
      prompt: "What is the largest segment?",
      criteria: ["names a segment", "gives a count"],
      criteriaAutoGenerated: false,
    };
    const u = buildJudgeUser(task, "The largest is VIP with 1200 profiles.");
    expect(u).toContain("What is the largest segment?");
    expect(u).toContain("1. names a segment");
    expect(u).toContain("VIP with 1200");
  });
  it("numbers multi-turn conversations", () => {
    const task: Task = {
      id: "t2",
      category: "medium",
      turns: ["first", "second"],
      criteria: ["ok"],
      criteriaAutoGenerated: false,
    };
    const u = buildJudgeUser(task, "answer");
    expect(u).toContain("Turn 1: first");
    expect(u).toContain("Turn 2: second");
  });
});
