import { writeFile } from "node:fs/promises";
import { stringify as yamlStringify } from "yaml";
import type { AuthMode, Task, TaskCategory, ToolDef } from "../types.js";
import { completeText, extractJson } from "../engine/complete.js";

const GEN_SYSTEM =
  "You design realistic evaluation tasks for an MCP (Model Context Protocol) server. " +
  "Given the server's tools, produce tasks a real user would ask that genuinely exercise those tools. " +
  "Mix single-turn and short multi-turn tasks. For each task include 3-5 concrete pass/fail criteria an " +
  "evaluator can check. Respond with ONLY JSON, no prose, no markdown:\n" +
  '{"tasks":[{"id":"kebab-id","category":"baseline|short|medium|long","prompt":"single-turn text",' +
  '"turns":["turn 1","turn 2"],"criteria":["...","..."]}]}\n' +
  "Use EITHER prompt (single-turn) OR turns (multi-turn) per task, not both. " +
  "category: baseline/short=1-2 turns, medium=~5, long=~10.";

function toolDigest(tools: ToolDef[]): string {
  return tools
    .map((t) => {
      const props = Object.keys((t.inputSchema?.properties as Record<string, unknown>) ?? {});
      return `- ${t.name}(${props.join(", ")}): ${t.description ?? "(no description)"}`;
    })
    .join("\n");
}

const CATEGORIES: TaskCategory[] = ["baseline", "short", "medium", "long"];

function normalize(raw: any, idx: number): Task | null {
  const prompt = typeof raw?.prompt === "string" ? raw.prompt : undefined;
  const turns = Array.isArray(raw?.turns) ? raw.turns.filter((t: unknown) => typeof t === "string") : undefined;
  if (!prompt && !(turns && turns.length)) return null;
  return {
    id: typeof raw?.id === "string" ? raw.id : `gen-${idx + 1}`,
    category: CATEGORIES.includes(raw?.category) ? raw.category : "short",
    prompt: turns && turns.length ? undefined : prompt,
    turns: turns && turns.length ? turns : undefined,
    criteria: Array.isArray(raw?.criteria) ? raw.criteria.filter((c: unknown) => typeof c === "string") : [],
    criteriaAutoGenerated: true,
  };
}

/** Synthesize a starter task suite from the server's tool surface. */
export async function generateTasks(
  tools: ToolDef[],
  opts: { count: number; model: string; auth: AuthMode },
): Promise<Task[]> {
  const user = `MCP SERVER TOOLS:\n${toolDigest(tools)}\n\nGenerate ${opts.count} tasks.`;
  const text = await completeText({ model: opts.model, auth: opts.auth, system: GEN_SYSTEM, user, maxTokens: 4096 });
  const obj = extractJson(text) as { tasks?: unknown[] } | null;
  const arr = Array.isArray(obj) ? obj : obj?.tasks;
  if (!Array.isArray(arr)) throw new Error("task generator returned no parseable tasks");
  const tasks = arr.map(normalize).filter((t): t is Task => t !== null);
  if (!tasks.length) throw new Error("task generator produced no valid tasks");
  return tasks;
}

/** Persist a generated suite as editable YAML (lab-compatible field names). */
export async function saveTasks(path: string, tasks: Task[]): Promise<void> {
  const doc = tasks.map((t) => ({
    id: t.id,
    category: t.category,
    ...(t.prompt ? { prompt: t.prompt } : {}),
    ...(t.turns ? { turns: t.turns } : {}),
    criteria: t.criteria,
  }));
  await writeFile(path, yamlStringify(doc), "utf8");
}
