import { readFile, readdir, stat } from "node:fs/promises";
import { join, extname } from "node:path";
import { parse as parseYaml } from "yaml";
import type { Task, TaskCategory, TaskExpectations } from "../types.js";

const CATEGORIES: TaskCategory[] = ["baseline", "short", "medium", "long"];

/** Raw task shape accepted from BYO files — supports lab field names and ours. */
interface RawTask {
  id?: string;
  category?: string;
  prompt?: string;
  user_prompt?: string;
  turns?: string[];
  user_turns?: string[];
  criteria?: string[];
  judge_criteria?: string[];
  expect?: TaskExpectations;
  expectations?: TaskExpectations;
  notes?: string;
}

function normalize(raw: RawTask, idx: number): Task {
  const id = raw.id ?? `task-${idx + 1}`;
  const prompt = raw.prompt ?? raw.user_prompt;
  const turns = raw.turns ?? raw.user_turns;
  if (!prompt && !(turns && turns.length)) {
    throw new Error(`Task "${id}" has neither prompt/user_prompt nor turns/user_turns`);
  }
  const category = (CATEGORIES as string[]).includes(raw.category ?? "")
    ? (raw.category as TaskCategory)
    : "short";
  return {
    id,
    category,
    prompt: turns && turns.length ? undefined : prompt,
    turns: turns && turns.length ? turns : undefined,
    criteria: raw.criteria ?? raw.judge_criteria ?? [],
    criteriaAutoGenerated: false,
    expect: raw.expect ?? raw.expectations,
    notes: raw.notes,
  };
}

async function parseFile(path: string): Promise<RawTask[]> {
  const text = await readFile(path, "utf8");
  const ext = extname(path).toLowerCase();
  const data = ext === ".yaml" || ext === ".yml" ? parseYaml(text) : JSON.parse(text);
  return Array.isArray(data) ? data : [data];
}

/**
 * Load a BYO workload. `path` may be a single yaml/json file (array or single
 * task) or a directory of *.json/*.yaml task files.
 */
export async function loadTasks(path: string): Promise<Task[]> {
  const info = await stat(path);
  const raws: RawTask[] = [];
  if (info.isDirectory()) {
    const files = (await readdir(path))
      .filter((f) => [".json", ".yaml", ".yml"].includes(extname(f).toLowerCase()))
      .sort();
    for (const f of files) raws.push(...(await parseFile(join(path, f))));
  } else {
    raws.push(...(await parseFile(path)));
  }
  const tasks = raws.map(normalize);
  if (tasks.length === 0) throw new Error(`No tasks found at ${path}`);
  return tasks;
}
