/**
 * Core data shapes shared across mcp-dyno.
 *
 * Conventions:
 *  - "billable tokens" = input + cache_creation + output  (cache_read excluded)
 *  - context-bloat is decomposed into 4 channels: tool-defs / tool-args / tool-results / reasoning
 */

// ---------------------------------------------------------------------------
// Server connection
// ---------------------------------------------------------------------------

export type Transport = "stdio" | "sse" | "http";

export interface ServerSpec {
  /** For stdio: the shell command to launch (e.g. "node ./build/index.js"). For sse/http: the URL. */
  target: string;
  transport: Transport;
  /** Extra env vars for a stdio child process. */
  env?: Record<string, string>;
  /** Headers for sse/http (auth, etc.). */
  headers?: Record<string, string>;
  /** Optional human label, e.g. "base" / "head" in compare mode. */
  label?: string;
}

/** A tool as advertised by the MCP server. */
export interface ToolDef {
  name: string;
  description?: string;
  inputSchema: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Workload
// ---------------------------------------------------------------------------

export type TaskCategory = "baseline" | "short" | "medium" | "long";

/** Deterministic, ground-truth checks (no LLM judge needed). All optional. */
export interface TaskExpectations {
  /** Each named tool must be called at least once. */
  toolsCalled?: string[];
  /** The final answer must contain each substring (case-insensitive). */
  answerContains?: string[];
  /** The final answer must match each regular expression (case-insensitive). */
  answerMatches?: string[];
}

export interface Task {
  id: string;
  category: TaskCategory;
  /** Single-turn prompt. Exactly one of `prompt` / `turns` is set. */
  prompt?: string;
  /** Multi-turn conversation (each string is one user turn). */
  turns?: string[];
  /** Natural-language pass/fail criteria for the LLM judge. */
  criteria: string[];
  /** True when criteria were synthesized by the tool (correctness is then "indicative"). */
  criteriaAutoGenerated: boolean;
  /** Deterministic checks; when present they score correctness directly (judge not needed). */
  expect?: TaskExpectations;
  notes?: string;
}

// ---------------------------------------------------------------------------
// Auth / model
// ---------------------------------------------------------------------------

export type AuthMode = "api" | "cli";

export interface RunConfig {
  server: ServerSpec;
  tasks: Task[];
  epochs: number;
  /** Driver model id (Claude only in v1). */
  model: string;
  /** Judge model — deliberately not the same tier as the driver, to avoid self-enhancement bias. */
  judgeModel: string;
  auth: AuthMode;
  /** Max concurrent attempts. */
  concurrency: number;
  /** Output directory for run artifacts. */
  outDir: string;
}

// ---------------------------------------------------------------------------
// Raw interaction transcript (driver-agnostic)
// ---------------------------------------------------------------------------

export type ToolCall = {
  name: string;
  /** Raw argument JSON the model emitted. */
  args: unknown;
  /** Raw result content returned by the server (stringified). */
  result?: string;
  isError?: boolean;
  durationMs?: number;
};

export interface TurnTranscript {
  userPrompt: string;
  assistantText: string;
  toolCalls: ToolCall[];
  usage: TokenUsage;
}

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  cacheCreationTokens: number;
  cacheReadTokens: number;
}

/** The full record a ModelDriver returns for one task attempt. */
export interface Transcript {
  finalText: string;
  turns: TurnTranscript[];
  /** Exact tool definitions sent to the model (known precisely in API mode). */
  toolDefs: ToolDef[];
  /** True when decomposition is estimated rather than exact (CLI/subscription mode). */
  estimated: boolean;
  durationMs: number;
  /** Cost in USD if the driver reports it directly (Claude CLI result event). */
  reportedCostUsd?: number;
}

// ---------------------------------------------------------------------------
// Measurement
// ---------------------------------------------------------------------------

/** Headline efficiency signals (port of decompose.extract_efficiency). */
export interface EfficiencySignals {
  /** input + cache_creation + output */
  totalTokens: number;
  cacheReadTokens: number;
  durationMs: number;
  toolCalls: number;
  discoveryRoundtrips: number;
  refetchRoundtrips: number;
  turns: number;
}

export type Channel = "toolDef" | "toolArg" | "toolResult" | "reasoning";

/** 4-channel context-bloat decomposition (port of decompose.decompose_cell). */
export interface Decomposition {
  bytes: Record<Channel, number> & { total: number };
  shares: Record<Channel, number>;
  tokensEst: Record<Channel, number>;
  usage: {
    billableTotal: number;
    cacheReadTokens: number;
    cacheReadShare: number;
    attributedTokens: number;
    floorTokens: number;
    attributableShare: number;
  };
  estimated: boolean;
}

/** Objective, ground-truth-free structural checks. */
export interface StructuralFlags {
  hallucinatedToolCalls: number;
  schemaViolations: number;
  toolErrors: number;
  recoveredFromError: boolean;
}

// ---------------------------------------------------------------------------
// Server Ergonomics — design-quality signals attributed to the server, not the
// model. Computed per attempt from the full transcript, then aggregated per tool.
// ---------------------------------------------------------------------------

/** Per-attempt ergonomics, captured before transcript truncation. */
export interface AttemptErgonomics {
  /** Per tool name: how many times it was called this attempt and the result-token cost. */
  perTool: Record<string, { calls: number; resultTokens: number; resultTokensMax: number }>;
  /** The very first tool call of the attempt (affordance: did the model start correctly?). */
  firstCall: { name: string; errored: boolean; schemaViolated: boolean } | null;
  /** First use of each distinct tool within the attempt (clarity of that tool's contract). */
  firstCallByTool: Record<string, { errored: boolean; schemaViolated: boolean }>;
}

/** Aggregated ergonomics for one tool across all attempts. */
export interface ToolErgonomics {
  name: string;
  calls: number;
  /** Result-payload efficiency: mean/max tokens returned per call, and share of all result tokens. */
  resultTokensMean: number;
  resultTokensMax: number;
  resultTokenShare: number;
  heavyPayload: boolean;
  /** Affordance clarity: among first uses of this tool, how often args were malformed / the call errored. */
  firstCalls: number;
  firstCallSchemaErrorRate: number;
  firstCallErrorRate: number;
}

/** Server-level ergonomics summary + the per-tool "design worklist". */
export interface ErgonomicsSummary {
  perTool: ToolErgonomics[];
  /** Fraction of attempts whose FIRST tool call was a known tool with valid args and no error. */
  firstCallSuccessRate: number | null;
  /** Worklist: tools whose results are large enough to warrant pagination / field-selection. */
  heavyPayloadTools: string[];
  /** Worklist: tools the model frequently mis-invokes on first reach (description/schema unclear). */
  unclearTools: string[];
  payloadThresholdTokens: number;
}

export type Verdict = "PASS" | "PARTIAL" | "FAIL";

export interface JudgeResult {
  criterion: string;
  verdict: Verdict;
  reason: string;
}

/** A human-readable transcript of one attempt, persisted so the dashboard can
 * show the full request/response log. Long strings are truncated. */
export interface ToolCallLog {
  name: string;
  args: unknown;
  result: string;
  isError: boolean;
}
export interface TurnLog {
  userPrompt: string;
  assistantText: string;
  toolCalls: ToolCallLog[];
}
export interface AttemptLog {
  turns: TurnLog[];
  finalText: string;
}

/** One task × epoch attempt, fully measured. */
export interface AttemptResult {
  taskId: string;
  epoch: number;
  signals: EfficiencySignals;
  decomposition: Decomposition;
  structural: StructuralFlags;
  /** Per-attempt Server Ergonomics signals (absent on attempts from pre-0.2 runs). */
  ergonomics?: AttemptErgonomics;
  judge: JudgeResult[];
  /** 0..1 correctness from judge verdicts; null when the judge was not run. */
  score: number | null;
  /** Cost in USD for this attempt (CLI-reported or priced from token usage). */
  costUsd?: number;
  /** Full request/response transcript (truncated) for dashboard drill-down. */
  log?: AttemptLog;
  failed: boolean;
  error?: string;
}
